name: dartling_skeleton
version: 0.0.9
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling is a domain model framework. A new dartling project is copied and adapted from dartling_skeleton.
homepage: http://ondart.me/
dependencies:
  browser: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
